Sim Clustering
PFCal-dev/cmssw pull request #68
Opened 2016-10-18 17:03 UTC by amarini

First version,
don't merge yet.

#19

2016-10-18 17:07 UTC, lgray commented
I'll take a look too in the next days. Thanks a lot for this!

2016-10-18 19:36 UTC, jbsauvan commented
Thanks @amarini. I'll have a look tomorrow.

2016-10-19 14:45 UTC, jbsauvan requested changes

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendAlgorithmBase.h
> +    name_(conf.getParameter<std::string>("AlgorithmName"))
Initialize the geometry_ to null

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendAlgorithmBase.h
> +                   const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
Not needed. The geometry is already available as member of the class.

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendProcessor.h
> +           const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
Geometry not needed

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/HGCalTriggerDigiFEReproducer.cc
> +    backEndProcessor_->run(fe_digis_coll,triggerGeometry_,e);
Not needed to pass the geometry

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/HGCalTriggerDigiProducer.cc
> +  backEndProcessor_->run(fe_digis_coll,triggerGeometry_,e);
ditto

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/FullModuleSumAlgo.cc
> +                const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
ditto

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/src/HGCalTriggerBackendProcessor.cc
> +    const edm::ESHandle<HGCalTriggerGeometryBase> & geom,
geometry not needed

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +#ifdef DEBUG
I guess the DEBUG flags and cout will be removed

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            std::unique_ptr<l1t::HGCalClusterBxCollection> cluster_product;
Use trailing underscore for data member names

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            auto iterator = cluster_container.find (pid);
Use emplace. It will insert the new element if it doesn't already exist and return the iterator. If the element already exists it will do nothing and return the iterator to the existing element. So it will do in one step what you are doing with find() + [] + find()

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            math::PtEtaPhiMLorentzVectorD p4;
Is there a reason to copy in a temporary variable the 4-vector contained in the map?

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            using Algorithm<FECODEC>::codec_;
What is the purpose of these using declarations?

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                if (not sim_handle.isValid()) { std::cout<<"[HGCalTriggerSimCluster]::[run]::[ERROR] PFCluster collection for HGC sim clustering not available"<<std::endl; throw 39;}
Use cms::Exception

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                    const HGCTriggerDetId& moduleId = digi.getDetId<HGCTriggerDetId>(); // this is a module Det Id
moduleId doesn't seem to be used

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                            auto digiEnergy=triggercell.p4().E();
energy, eta, phi can be directly accessed from HGCalTriggerCell.
Also note that the energy here is the hardware value.

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                const auto& particles =  simclusters[cellId]; // vector pid fractions
Is it ensured that cellId is in the simClusters map?

2016-10-19 14:45 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                    auto energy = fraction*digiEnergy;
What exactly is this energy?

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendAlgorithmBase.h
> +    name_(conf.getParameter<std::string>("AlgorithmName"))
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendAlgorithmBase.h
> +                   const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendProcessor.h
> +           const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/plugins/HGCalTriggerDigiFEReproducer.cc
> +    backEndProcessor_->run(fe_digis_coll,triggerGeometry_,e);
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/plugins/HGCalTriggerDigiProducer.cc
> +  backEndProcessor_->run(fe_digis_coll,triggerGeometry_,e);
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/FullModuleSumAlgo.cc
> +                const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/src/HGCalTriggerBackendProcessor.cc
> +    const edm::ESHandle<HGCalTriggerGeometryBase> & geom,
+1

2016-10-20 13:39 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            auto iterator = cluster_container.find (pid);
+1

2016-10-20 13:46 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            math::PtEtaPhiMLorentzVectorD p4;
Is it defined the sum of two Candidates ? (operator += ? )

2016-10-20 13:47 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            using Algorithm<FECODEC>::codec_;
They are needed for how it is structured the code. (C++)

2016-10-20 13:47 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +#ifdef DEBUG
I think I will remove them, but if there is no DEBUG flag defined the compiler will ignore that code.

2016-10-20 13:48 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                    const HGCTriggerDetId& moduleId = digi.getDetId<HGCTriggerDetId>(); // this is a module Det Id
+1, was a residual from the previous FE codec implementation.

2016-10-20 13:50 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                            auto digiEnergy=triggercell.p4().E();
what is the difference among the two ?  (p4.E(), E() ? )

2016-10-20 13:51 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                const auto& particles =  simclusters[cellId]; // vector pid fractions
I'll put a protection to avoid the map growing. But from the logical point of view is fine.

2016-10-20 13:51 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                    auto energy = fraction*digiEnergy;
This is the energy we want.

2016-10-20 14:27 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +            math::PtEtaPhiMLorentzVectorD p4;
I don't think there is a += operator for candidates. But something like that should work:
```c++
pp4 += iterator -> second . second .p4();
iterator -> second . second . setP4(pp4);
```
This way you don't need to copy into p4

2016-10-20 14:49 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                            auto digiEnergy=triggercell.p4().E();
`triggercell.energy()` gives the energy of the 4-vector (so same as `triggercell.p4().E()`)

2016-10-20 14:55 UTC, jbsauvan commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                    auto energy = fraction*digiEnergy;
Thanks :-)
But here digiEnergy is the trigger cell energy and it seems like you add it to the cluster for each cell inside the trigger cell (the `addToCluster` call is done inside the cell loop). Naively I would think that the same energy is counted multiple times.

2016-11-02 07:36 UTC, jbsauvan commented
@amarini is there any update on this PR?

2016-11-02 12:57 UTC, amarini commented on L1Trigger/L1THGCal/plugins/be_algorithms/HGCalSimCluster.cc
> +                                    auto energy = fraction*digiEnergy;
ok, this is not correct at the moment, I will avarage through the cells.

2016-11-03 13:30 UTC, jbsauvan commented
@amarini Do you have already some test class?

2016-11-03 13:34 UTC, amarini commented
Hi, not yet. I plan to do it next week.
Can you check if there is some residual fix to be applied?

2016-11-03 13:48 UTC, jbsauvan commented
Ok, thanks.
The remaining things that I see are:
* Avoid unnecessary 4-vector copy in `addToCluster`
* Cleaning and standardization (e.g., use edm::LogDebug for debug output if you wish to keep them and cms::Exception for exceptions)
* Rebase your updates on top of the main devel branch since there are conflicts

2016-11-14 08:25 UTC, jbsauvan commented
Hi @amarini 
Any progress on this PR?

2016-11-23 10:25 UTC, amarini commented
Progressing:
![schermata 2016-11-23 alle 11 24 08](https://cloud.githubusercontent.com/assets/4516989/20558285/853e78f6-b16f-11e6-91d1-695232f6cb78.png)

2016-11-23 12:14 UTC, jbsauvan commented
@amarini 
In case you would like to have more meaningful energies, Luca has implemented the trigger cell calibration. It is for instance used here:
https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_8_1_0_pre12/L1Trigger/L1THGCal/plugins/be_algorithms/SingleCellClusterAlgo.cc#L62

2016-12-07 07:22 UTC, jbsauvan commented
Hi @amarini, 
do you think this PR could be integrated before the Christmas break?

2016-12-07 08:44 UTC, amarini commented
Yes i ll try to have it asap.
A

Il 07 dicembre 2016 08:22:15 CET, Jean-Baptiste Sauvan <notifications@github.com> ha scritto:
>Hi @amarini, 
>do you think this PR could be integrated before the Christmas break?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PFCal-dev/cmssw/pull/68#issuecomment-265375079

-- Inviato dal mio cellulare Android con K-9 Mail.

2016-12-07 08:45 UTC, jbsauvan commented
ok, thanks

2016-12-15 08:30 UTC, jbsauvan commented
@amarini, is it in a close to final state? Can it be reviewed now or should I wait other commits?
Thanks,
Jean-Baptiste

2016-12-15 09:57 UTC, amarini commented
![schermata 2016-12-15 alle 10 57 22](https://cloud.githubusercontent.com/assets/4516989/21219482/46ca34d2-c2b5-11e6-8809-471e580628ed.png)

I will remove the debug lines, but apart from that you can review it.

2016-12-15 13:31 UTC, lgray commented
Hi Andrea,

Can you give some description of the plots? Are these supposed to be photon
gun or jets or what?

-L

On Thu, Dec 15, 2016 at 3:57 AM, Andrea Marini <notifications@github.com>
wrote:

> [image: schermata 2016-12-15 alle 10 57 22]
> <https://cloud.githubusercontent.com/assets/4516989/21219482/46ca34d2-c2b5-11e6-8809-471e580628ed.png>
>
> I will remove the debug lines, but apart from that you can review it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PFCal-dev/cmssw/pull/68#issuecomment-267287325>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABBMOT80LK1LWeH7zVROeZO8QCEjaVhZks5rIQ8egaJpZM4KaC5y>
> .
>

2016-12-15 14:08 UTC, amarini commented
Hi,

this is Single Photon Gun (pT=35GeV), in particular with generation parameters:

~~~python
    PGunParameters = cms.PSet(
        MaxEta = cms.double(5.0),
        MaxPhi = cms.double(3.14159265359),
        MaxPt = cms.double(35.01),
        MinEta = cms.double(3.0),
        MinPhi = cms.double(-3.14159265359),
        MinPt = cms.double(34.99),
        PartID = cms.vint32(22)
~~~

there is still something to be understood, in what regards the energy and the reconstruction in general.

2016-12-15 14:09 UTC, lgray commented
Why is max eta = 5 and min eta = 3? This complete misses the calorimeter!

On Thu, Dec 15, 2016 at 8:08 AM, Andrea Marini <notifications@github.com>
wrote:

> Hi,
>
> this is Single Photon Gun (pT=35GeV), in particular with generation
> parameters:
>
>     PGunParameters = cms.PSet(
>         MaxEta = cms.double(5.0),
>         MaxPhi = cms.double(3.14159265359 <(415)%20926-5359>),
>         MaxPt = cms.double(35.01),
>         MinEta = cms.double(3.0),
>         MinPhi = cms.double(-3.14159265359 <(415)%20926-5359>),
>         MinPt = cms.double(34.99),
>         PartID = cms.vint32(22)
>
> there is still something to be understood, in what regards the energy and
> the reconstruction in general.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PFCal-dev/cmssw/pull/68#issuecomment-267335743>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABBMOU9e5Jb13EsVrMZma21ONQgWV8p6ks5rIUntgaJpZM4KaC5y>
> .
>

2016-12-15 14:13 UTC, amarini commented
minEta 1.4 and maxEta should be 3.0, correct?

2016-12-15 14:17 UTC, lgray commented
Given the tiling of only full hexgons, the fiducial value is something like
1.6 < |eta| < 2.8.

On Thu, Dec 15, 2016 at 8:13 AM, Andrea Marini <notifications@github.com>
wrote:

> minEta 1.4 and maxEta should be 3.0, correct?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PFCal-dev/cmssw/pull/68#issuecomment-267336841>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABBMORmOBfORU6WFhup9KzhmmWVzrwjqks5rIUsIgaJpZM4KaC5y>
> .
>

2016-12-15 16:27 UTC, amarini commented
![schermata 2016-12-15 alle 17 28 21](https://cloud.githubusercontent.com/assets/4516989/21232400/c63bcb3c-c2eb-11e6-90d1-52627112d6f3.png)

2016-12-16 08:47 UTC, jbsauvan commented
@amarini to have sensible energies you need to call the trigger cell calibration implemented by @mastrolorenzo (example [here](https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_8_1_0_pre12/L1Trigger/L1THGCal/plugins/be_algorithms/SingleCellClusterAlgo.cc#L62))

2016-12-16 13:49 UTC, jbsauvan commented on L1Trigger/L1THGCal/interface/HGCalTriggerBackendProcessor.h
> +           const edm::ESHandle<HGCalTriggerGeometryBase>& geom,
Passing the geometry is not needed

2016-12-16 13:53 UTC, jbsauvan commented
I tried to run the `testTriggerSimCluster.py` script but it throws some error:
> File "testTriggerSimCluster.py", line 42, in <module>
    print "product", clusters.product()[bx]
SystemError: none of the 2 overloaded methods succeeded. Full details:
  l1t::HGCalCluster& BXVector<l1t::HGCalCluster>::operator[](unsigned long i) =>
    could not convert argument 1 (Objects/longobject.c:426: bad argument to internal function)
  const l1t::HGCalCluster& BXVector<l1t::HGCalCluster>::operator[](unsigned long i) =>
    could not convert argument 1 (Objects/longobject.c:426: bad argument to internal function)

2016-12-19 12:21 UTC, amarini commented
![schermata 2016-12-19 alle 13 14 24](https://cloud.githubusercontent.com/assets/4516989/21312654/b6f901d0-c5ed-11e6-8f35-d606f0059cd8.png)

I add the energy calibration, and now the test module should work. Pt, E and Phi are for the objects with eta<10. Still something to understand better.

I'll remove the geometry handle asap. I kept them because was easier to merge.

2017-01-04 17:10 UTC, jbsauvan commented
Thanks for the updates. I'll try to investigate as well the strange things that you are seeing.
Just to be sure, the normalization update is just for debugging?

2017-01-04 17:43 UTC, amarini commented
Hi,
Yes. I wanted to be 100% sure that the normalization was one.Ill have some small changes in order to have cluster information, I ll push everything in the weekend, but nothing changed the picture on the energy.
Andrea


Inviato da Tablet Samsung.

-------- Messaggio originale --------
Da: Jean-Baptiste Sauvan <notifications@github.com> 
Data: 04/01/2017  18:10  (GMT+01:00) 
A: PFCal-dev/cmssw <cmssw@noreply.github.com> 
Cc: Andrea Marini <andrea.marini@cern.ch>, Mention <mention@noreply.github.com> 
Oggetto: Re: [PFCal-dev/cmssw] Sim Clustering (#68) 

Thanks for the updates. I'll try to investigate as well the strange things that you are seeing.

Just to be sure, the normalization update is just for debugging?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PFCal-dev/cmssw","title":"PFCal-dev/cmssw","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PFCal-dev/cmssw"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbsauvan in #68: Thanks for the updates. I'll try to investigate as well the strange things that you are seeing.\r\nJust to be sure, the normalization update is just for debugging?"}],"action":{"name":"View Pull Request","url":"https://github.com/PFCal-dev/cmssw/pull/68#issuecomment-270426641"}}}

2017-01-19 11:07 UTC, jbsauvan commented
@amarini I moved the development branch to 9_0_0_pre2 (hgc-tpg-devel-CMSSW_9_0_0_pre2). So when ready this work should be put in an other PR.

2017-02-14 16:50 UTC, closed without merging